CREATE TABLE IF NOT EXISTS users (
    id VARCHAR PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE,
    avatar_url VARCHAR NOT NULL,
    github_id VARCHAR NOT NULL UNIQUE,
    access_token VARCHAR NOT NULL UNIQUE,
    email VARCHAR NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 