name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - 'main' 
      - 'feat-ci'
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # Allow pushing to GHCR

jobs:
  build_and_push:
    runs-on: self-hosted-hetzner  # Use your self-hosted runner
    timeout-minutes: 30   # Prevent hung jobs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get secrets from AWS Secrets Manager
      id: get_secrets
      run: |
        if ! aws secretsmanager get-secret-value \
          --secret-id arn:aws:secretsmanager:ap-southeast-1:351138146362:secret:prod/faucet/monad-be-JZa8j2 \
          --query 'SecretString' --output text \
          --region ap-southeast-1 > secrets.json; then
          echo "Failed to fetch secrets from AWS Secrets Manager"
          exit 1
        fi

    - name: Write secrets to .env file
      run: |
        echo "Writing secrets to .env file"
        cat secrets.json | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > .env

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image and push to GHCR
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/catalogfi/monad-faucet-be:prod
          ghcr.io/catalogfi/monad-faucet-be:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max